import type { ShoppingState } from '@/src/features/shopping/shopping.type.ts';

export const SHOPPING_STATE: ShoppingState = {
  algorithmicTrading: {
    category: 'investing',
    cost: [{ asset: 'operation', cost: 1e4 }],
    active: false,
    effect: ['investments'],
    available: false,
    quantity: 1,
    requirement: [{ asset: 'trust', cost: 8 }],
  },
  begForMoreWire: {
    category: 'wire',
    cost: [{ asset: 'trust', cost: 1 }],
    active: false,
    effect: [{ asset: 'funds', cost: 100 }],
    available: false,
    quantity: 5,
  },
  catchyJingle: {
    category: 'marketing',
    cost: [
      { asset: 'operation', cost: 75e2 },
      { asset: 'creativity', cost: 45 },
    ],
    active: false,
    effect: ['hypnoHarmonics'],
    available: false,
    quantity: 1,
    // requirement: ['combinatoryHarmonics'],
  },
  clipper: { active: false, available: false, requirement: [{ asset: 'funds', cost: 5 }] },
  swarm: { active: false, available: false },
  clipFactory: { active: false, available: false }, // requirement: ['wireDroneProcess']
  fullMonopoly: {
    category: 'marketing',
    cost: [
      { asset: 'funds', cost: 1e7 },
      { asset: 'yomi', cost: 3e3 },
    ],
    active: false,
    effect: [
      { asset: 'marketingBonus', cost: 1e2 },
      { asset: 'trust', cost: 1 },
    ],
    available: false,
    requirement: [{ asset: 'funds', cost: 1e7 }],
  },
  fundsPerSecond: { active: false, available: false },
  harvesterDrone: { active: false, available: false },
  harvesterDroneProcess: {
    category: 'drones',
    cost: [{ asset: 'operation', cost: 25e3 }],
    active: false,
    effect: ['harvesterDrone'],
    available: false,
    quantity: 1,
    // requirement: ['releaseHypnoDrone']
  },
  hostileTakeover: {
    category: 'marketing',
    cost: [{ asset: 'funds', cost: 1e6 }],
    active: false,
    effect: [
      { asset: 'marketingBonus', cost: 10 },
      { asset: 'trust', cost: 1 },
    ],
    available: false,
    requirement: [{ asset: 'funds', cost: 1e7 }],
  },
  hypnoHarmonics: {
    category: 'marketing',
    cost: [
      { asset: 'operation', cost: 75e2 },
      { asset: 'trust', cost: 1 },
    ],
    active: false,
    effect: ['hypnoDrone'],
    available: false,
    quantity: 1,
    // requirement: ['catchyJingle'],
  },
  hypnoDrone: {
    category: 'drones',
    cost: [{ asset: 'operation', cost: 7e4 }],
    active: false,
    effect: ['releaseHypnoDrone'],
    available: false,
    quantity: 1,
    // requirement: ['hypnoHarmonics'],
  },
  improvedClipper: {
    category: 'production',
    cost: [{ asset: 'operation', cost: 750 }],
    active: false,
    effect: [{ asset: 'clipperBonus', cost: 2 }],
    available: false,
    quantity: 1,
    requirement: [{ asset: 'operation', cost: 750 }],
  },
  investments: { active: false, available: false }, // requirement: ['algorithmicTrading']
  megaClipper: { active: false, available: false, requirement: [{ asset: 'clipper', cost: 75 }] },
  marketing: { active: false, available: false, requirement: [{ asset: 'funds', cost: 200 }] },
  newSlogan: {
    category: 'marketing',
    cost: [
      { asset: 'operation', cost: 25e2 },
      { asset: 'creativity', cost: 25 },
    ],
    active: false,
    effect: [{ asset: 'marketingBonus', cost: 2 }],
    available: false,
    quantity: 1,
    // requirement: ['lexicalProcessing'],
  },
  offerAnotherChance: {
    category: 'mechanic',
    cost: [{ asset: 'creativity', cost: 7e4 }],
    active: false,
    // effect: { type: 'ALLOCATE_TRUST' },
    available: false,
    quantity: 10,
    requirement: [{ asset: 'creativity', cost: 7e4 }],
  },
  production: { active: false, available: false },
  releaseHypnoDrone: {
    category: 'drones',
    cost: [{ asset: 'trust', cost: 1e2 }],
    active: false,
    effect: ['harvesterDroneProcess', 'wireDroneProcess'],
    available: false,
    // requirement: ['hypnoDrone']
  },
  resources: {
    active: false,
    available: false,
    requirement: [{ asset: 'clip', cost: 2e3 }],
  },
  revTracker: {
    category: 'mechanic',
    cost: [{ asset: 'operation', cost: 5e2 }],
    active: true,
    effect: ['fundsPerSecond'],
    available: true,
    quantity: 1,
  },
  spaceExploration: { active: false, available: false },
  swarmGifts: { active: false, available: false },
  wireDrone: { active: false, available: false },
  wireDroneProcess: {
    category: 'drones',
    cost: [{ asset: 'operation', cost: 25e3 }],
    active: false,
    effect: ['wireDrone', 'clipFactory'],
    available: false,
    quantity: 1,
    // requirement: ['releaseHypnoDrone']
  },
};
