import type { FeatureState } from '@/src/domains/factory/domain/feature.type.ts';
import type { ProductState } from '@/src/domains/factory/domain/product.type.ts';
import type { WalletState } from '@/src/domains/factory/domain/wallet.type.ts';

export interface FactoryState {
  acquiredMatter: number;
  availableMatter: number;
  cash: number;
  cashRef: number;
  clip: number;
  clipFactory: number;
  clipFactoryBonus: number;
  clipFactoryCost: number;
  clipPerSecond: number;
  clipPrice: number;
  clipPriceRef: number;
  creativity: number;
  clipper: number;
  clipperBonus: number;
  clipperCost: number;
  disorganization: number;
  entertainment: number;
  entertainmentCost: number;
  feature: FeatureState;
  funds: number;
  fundsPerSecond: number;
  harvesterDrone: number;
  harvesterDroneCost: number;
  matterPerSecond: number;
  marketing: number;
  marketingBonus: number;
  marketingCost: number;
  megaClipper: number;
  megaClipperBonus: number;
  megaClipperCost: number;
  memory: number;
  operation: number;
  operationMax: number;
  processor: number;
  product: ProductState;
  publicDemand: number;
  synchronizationCost: number;
  swarmGifts: number;
  swarmStrategy: number;
  trust: number;
  trustRef: number;
  universeMatter: number;
  unsoldInventory: number;
  unsoldInventoryBonus: number;
  wallet: WalletState;
  wire: number;
  wireCost: number;
  wireDrone: number;
  wireDroneCost: number;
  wirePerSecond: number;
  wireQuantity: number;
  yomi: number;
}
