import type { Translation } from '@/src/shared/types/translation.ts';

export const en: Translation = {
  store: {
    revTracker: {
      title: 'rev tracker',
      effect: 'allows to automatically calculate the average funds available per second',
      cost: 'cost: <cost />operation',
      quantity: 'quantity: <quantity />',
    },
    offerAnotherChance: {
      title: 'offer another chance',
      effect: 'reallocate accumulated trust for processor and memory specification',
      cost: 'cost: <cost />creativity',
      quantity: 'quantity: <quantity />',
    },
    begForMoreWire: {
      title: 'beg for more wire',
      effect: 'admit failure, ask for budget increase to cover cost of <effect /> wire',
      cost: 'cost: <cost /> trust',
      quantity: 'quantity: <quantity />',
    },
    improvedWireExtrusion: {
      title: 'improved wire extrusion',
      effect: 'increase the purchase of wire by <effect />',
      cost: 'cost: <cost /> operation',
      quantity: 'quantity: <quantity />',
    },
    algorithmicTrading: {
      title: 'algorithmic trading',
      effect: 'opens the option to invest your earnings in a rudimentary stock market',
      cost: 'cost: <cost /> operation',
      quantity: 'quantity: <quantity />',
    },
    improvedClipper: {
      title: 'improved clipper',
      effect: 'increases clipper performance by <effect />',
      cost: 'cost: <cost />operation',
      quantity: 'quantity: <quantity />',
    },
    evenBetterClipper: {
      title: 'even better clipper',
      effect: 'increases clipper performance by <effect /> time',
      cost: 'cost: <cost /> operation',
      quantity: 'quantity: <quantity />',
    },
    optimizedClipper: {
      title: 'optimized clipper',
      effect: 'increases clipper performance by <effect /> time',
      cost: 'cost: <cost /> operation',
      quantity: 'quantity: <quantity />',
    },
    clipperDiagrams: {
      title: 'clipper diagrams',
      effect: 'increases clipper performance by <effect /> time',
      cost: 'cost: <cost /> operation',
      quantity: 'quantity: <quantity />',
    },
    improvedMegaClipper: {
      title: 'improved mega clipper',
      effect: 'increases mega clipper performance by <effect /> time',
      cost: 'cost: <cost /> operation',
      quantity: 'quantity: <quantity />',
    },
    evenBetterMegaClipper: {
      title: 'even better mega clipper',
      effect: 'increases mega clipper performance by <effect /> time',
      cost: 'cost: <cost /> operation',
      quantity: 'quantity: <quantity />',
    },
    optimizedMegaClipper: {
      title: 'optimized mega clipper',
      effect: 'increases mega clipper performance by <effect /> time',
      cost: 'cost: <cost /> operation',
      quantity: 'quantity: <quantity />',
    },
    clipperMegaDiagrams: {
      title: 'mega clipper diagrams',
      effect: 'increases mega clipper performance by <effect /> time',
      cost: 'cost: <cost /> operation',
      quantity: 'quantity: <quantity />',
    },
    newSlogan: {
      title: 'new slogan',
      effect: 'selling price of clips effectiveness by <effect /> time',
      cost: 'cost: <cost /> operation',
      quantity: 'quantity: <quantity />',
    },
    catchyJingle: {
      title: 'catchy jingle',
      effect: 'double marketing efficiency allows for many other things',
      cost: 'cost: <cost /> creativity',
      quantity: 'quantity: <quantity />',
    },
    hypnoHarmonic: {
      title: 'hypo harmonic',
      effect: 'use neuron-resonant frequencies to influence consumer behavior',
      cost: 'cost: <cost /> operation',
      quantity: 'quantity: <quantity />',
    },
    hostileTakeover: {
      title: 'hostile takeover',
      effect: 'selling price of clips effectiveness <effect /> time and <kissCoolEffect /> trust',
      cost: 'cost: <cost />$',
      quantity: 'quantity: <quantity />',
    },
    fullMonopoly: {
      title: 'full monopoly',
      effect: 'selling price of clips effectiveness by <effect /> time and <kissCoolEffect /> trust',
      cost: 'cost: <cost /> yogis',
      quantity: 'quantity: <quantity />',
    },
    countyLimerick: {
      title: 'county limerick',
      effect: "there was an AI made of dust, whose poetry gained it man's trust (<effect />trust)",
      cost: 'cost: <cost /> creativity',
      quantity: 'quantity: <quantity />',
    },
    lexicalProcessing: {
      title: 'lexical processing',
      effect: 'gain ability to interpret and understand human language (<effect />trust)',
      cost: 'cost: <cost /> creativity',
      quantity: 'quantity: <quantity />',
    },
    combinatorHarmonic: {
      title: 'combinator harmonic',
      effect: 'an IBM mainframe was programmed to sing in 1961 (<effect />trust)',
      cost: 'cost: <cost /> creativity',
      quantity: 'quantity: <quantity />',
    },
    hypnoDrone: {
      title: 'hypno drones',
      effect: 'autonomous aerial brand ambassadors',
      cost: 'cost: <cost /> operation',
      quantity: 'quantity: <quantity />',
    },
    releaseHypnoDrone: {
      title: 'release the hypno drones',
      effect: 'a new era begins',
      cost: 'cost: <cost /> trust',
      quantity: 'quantity: <quantity />',
    },
    harvesterDroneProcess: {
      title: 'harvester drone process',
      effect: 'gather raw matter and prepare it for processing',
      cost: 'cost: <cost />operation',
      quantity: 'quantity: <quantity />',
    },
    wireDroneProcess: {
      title: 'wire drone process',
      effect: 'process acquired matter into wire',
      cost: 'cost: <cost />operation',
      quantity: 'quantity: <quantity />',
    },
  },
};
