import type { Translation } from '@/src/shared/types/translation.ts';

export const en: Translation = {
  factory: {
    titlePage: 'factory',
    paperclips: '<clip /> paperclips',
    clipFactory: 'clipFactory',
    clipFactoryCost: 'clip factory cost',
    clipFactories: 'clip factories',
    creativity: 'creativity',
    clipper: 'clipper',
    clipperCost: 'clipper cost',
    clippers: 'clippers',
    disorganization: 'disorganization',
    synchronizationCost: 'synchronization cost',
    megaClipper: 'mega clipper',
    megaClipperCost: 'mega clipper cost',
    megaClippers: 'mega clipper',
    memory: 'memory',
    business: 'business',
    price: 'price',
    clipPrice: 'clip selling price',
    fundsAvailable: 'available funds',
    fundsPerSecond: 'funds per second',
    marketing: 'marketing',
    marketingCost: 'marketing cost',
    publicDemand: 'public demand',
    operation: 'operations',
    processor: 'processor',
    processors: 'processors',
    swarmGifts: 'swarm gifts',
    unsoldInventory: 'unsold inventory',
    drone: 'drones',
    wireDrone: 'wire drones',
    wireDroneCost: 'wire drone cost',
    harvesterDrone: 'harvester drones',
    harvesterDroneCost: 'harvester drone cost',
    increaseMarketing: 'increase marketing',
    increaseMemory: 'increase memory',
    increaseClipPrice: 'increase clip price',
    decreaseClipPrice: 'decrease clip price',
    increaseProcessor: 'increase processor',
    synchronize: 'synchronize',
    noSpace: 'no space',
    noResource: 'no resource',
  },
};
