import type { Translation } from '@/src/shared/types/translation.ts';

export const fr: Translation = {
  factory: {
    titlePage: 'usine',
    paperclips: '<clip /> trombones',
    clipFactory: 'clipFactory',
    clipFactoryCost: 'clipFactory cost',
    creativity: 'creativity',
    clipper: 'clipper',
    clipperCost: 'clipper cost',
    disorganization: 'disorganization',
    synchronizationCost: 'synchronization cost',
    megaClipper: 'megaClipper',
    megaClipperCost: 'megaClipper cost',
    memory: 'memory',
    business: 'business',
    price: 'price',
    clipPrice: 'clip selling price',
    fundsAvailable: 'available funds',
    fundsPerSecond: 'funds per second',
    marketing: 'marketing',
    marketingCost: 'marketing cost',
    publicDemand: 'public demand',
    operation: 'operation',
    processor: 'processor',
    processors: 'processors',
    swarmGifts: 'swarm gifts',
    unsoldInventory: 'unsold inventory',
    drone: 'drone',
    wireDrone: 'wire drones',
    wireDroneCost: 'wire drone cost',
    harvesterDrone: 'harvester drones',
    harvesterDroneCost: 'harvester drone cost',
    increaseMarketing: 'increase marketing',
    increaseMemory: 'increase memory',
    increaseClipPrice: 'increase clip price',
    decreaseClipPrice: 'decrease clip price',
    increaseProcessor: 'increase processor',
    synchronize: 'synchronize',
    noSpace: "pas d'espace",
    noResource: 'pas de ressource',
  },
};
