import type { Factory } from '@/src/features/factory/domain/Factory.ts';
import { FEATURE_STATE } from '@/src/features/factory/infrastructure/featureState.ts';
import { WALLET_STATE } from '@/src/features/factory/infrastructure/walletState.ts';

export const FACTORY_STATE: Factory = {
  acquiredMatter: 0,
  availableMatter: 6e48,
  cash: 0,
  cashRef: 0,
  clip: 0,
  clipFactory: 0,
  clipFactoryBonus: 0,
  clipFactoryCost: 1e5,
  clipPerSecond: 0,
  clipPrice: 0.2,
  clipPriceRef: 0.2,
  clipper: 0,
  clipperBonus: 0,
  clipperCost: 5,
  creativity: 0,
  disorganization: 0,
  entertainment: 1,
  entertainmentCost: 1e4,
  feature: FEATURE_STATE,
  funds: 0,
  fundsPerSecond: 0,
  harvesterDrone: 0,
  harvesterDroneCost: 1e4,
  matterPerSecond: 0,
  marketing: 0,
  marketingBonus: 0,
  marketingCost: 100,
  megaClipper: 0,
  megaClipperBonus: 0,
  megaClipperCost: 5e2,
  memory: 1,
  operation: 0,
  operationMax: 7e2,
  processor: 1,
  publicDemand: 0.5,
  synchronizationCost: 5e3,
  swarmGifts: 0,
  swarmStrategy: 0,
  trust: 0,
  trustRef: 0,
  universeMatter: 0,
  unsoldInventory: 0,
  unsoldInventoryBonus: 0,
  wallet: WALLET_STATE,
  wire: 100,
  wireCost: 20,
  wireDrone: 0,
  wireDroneCost: 1e4,
  wirePerSecond: 0,
  wireQuantity: 100,
  yomi: 1e4,
};
