import type { Commerce } from '@/src/domains/commerce/domaine/com.type.ts';

export const COMMERCE_STATE: Commerce = {
  revTracker: {
    category: 'mechanic',
    cost: { asset: 'operation', value: 5e2 },
    effect: ['fundsPerSecond'],
    available: true,
    quantity: 1,
  },
  offerAnotherChance: {
    category: 'mechanic',
    cost: { asset: 'creativity', value: 7e4 },
    effect: { type: 'ALLOCATE_TRUST' },
    available: true,
    quantity: 10,
    requirement: { asset: 'creativity', value: 7e4 },
  },
  algorithmic: {
    category: 'investing',
    cost: { asset: 'operation', value: 1e4 },
    effect: ['investments'],
    available: true,
    quantity: 0,
    requirement: { asset: 'trust', value: 8 },
  },
  catchyJingle: {
    category: 'marketing',
    cost: { asset: 'operation', value: 75e2 },

    effect: ['hypnoHarmonics'],
    available: true,
    quantity: 1,
    // requirement: 'combinatoryHarmonics',
  },
  fullMonopoly: {
    category: 'marketing',
    cost: { asset: 'funds', value: 1e7 },
    effect: [
      { asset: 'marketingBonus', value: 1e2 },
      { asset: 'trust', value: 1 },
    ],
    available: true,
    quantity: 1,
    requirement: { asset: 'funds', value: 1e7 },
  },
  harvesterDroneProcess: {
    category: 'drones',
    cost: { asset: 'operation', value: 25e3 },
    effect: ['harvesterDrone'],
    available: true,
    quantity: 1,
    // requirement: 'releaseHypnoDrone',
  },
  hostileTakeover: {
    category: 'marketing',
    cost: { asset: 'funds', value: 1e6 },
    effect: [
      { asset: 'marketingBonus', value: 10 },
      { asset: 'trust', value: 1 },
    ],
    available: true,
    quantity: 1,
    requirement: { asset: 'funds', value: 1e7 },
  },
  hypnoHarmonics: {
    category: 'marketing',
    cost: { asset: 'operation', value: 75e2 },
    effect: ['hypnoDrone'],
    available: true,
    quantity: 1,
    // requirement: 'catchyJingle',
  },
  hypnoDrone: {
    category: 'drones',
    cost: { asset: 'operation', value: 7e4 },
    effect: ['releaseHypnoDrone'],
    available: true,
    quantity: 1,
    // requirement: 'hypnoHarmonics',
  },
  improvedClipper: {
    category: 'production',
    cost: { asset: 'operation', value: 750 },
    effect: [{ asset: 'clipperBonus', value: 2 }],
    available: true,
    quantity: 1,
    requirement: { asset: 'operation', value: 750 },
  },
  evenBetterClipper: {
    category: 'production',
    cost: { asset: 'operation', value: 25e2 },
    effect: [{ asset: 'clipperBonus', value: 10 }],
    available: true,
    quantity: 1,
    // requirement: 'improvedClipper',
  },
  optimizedClipper: {
    category: 'production',
    cost: { asset: 'operation', value: 5e3 },
    effect: [{ asset: 'clipperBonus', value: 100 }],
    available: true,
    quantity: 1,
    // requirement: 'evenBetterClipper',
  },
  hadwigerClipDiagram: {
    category: 'production',
    cost: { asset: 'operation', value: 6e3 },
    effect: [{ asset: 'clipperBonus', value: 500 }],
    available: true,
    quantity: 1,
    // requirement: 'hadwigerProblem',
  },
  improvedMegaClipper: {
    category: 'production',
    cost: { asset: 'operation', value: 14e3 },
    effect: [{ asset: 'megaClipperBonus', value: 2 }],
    available: true,
    quantity: 1,
    // requirement: 'megaClipper',
  },
  evenBetterMegaClipper: {
    category: 'production',
    cost: { asset: 'operation', value: 17e3 },
    effect: [{ asset: 'megaClipperBonus', value: 10 }],
    available: true,
    quantity: 1,
    // requirement: 'improvedMegaClipper',
  },
  optimizedMegaClippers: {
    category: 'production',
    cost: { asset: 'operation', value: 195e2 },
    effect: [{ asset: 'megaClipperBonus', value: 100 }],
    available: true,
    quantity: 1,
    // requirement: 'evenBetterMegaClipper',
  },
  newSlogan: {
    category: 'marketing',
    cost: { asset: 'operation', value: 25e2 },
    effect: [{ asset: 'marketingBonus', value: 2 }],
    available: true,
    quantity: 1,
  },
  releaseHypnoDrone: {
    category: 'drones',
    cost: { asset: 'trust', value: 1e2 },
    effect: ['harvesterDroneProcess', 'wireDroneProcess'],
    available: true,
    quantity: 1,
  },
  begForMoreWire: {
    category: 'wire',
    cost: { asset: 'trust', value: 1 },
    effect: [{ asset: 'funds', value: 100 }],
    available: true,
    quantity: 5,
  },
  improvedWireExtrusion: {
    category: 'wire',
    cost: { asset: 'operation', value: 1750 },
    effect: [{ asset: 'wireQuantity', value: 5e2 }],
    available: true,
    quantity: 1,
  },
  optimizedWireExtrusion: {
    category: 'wire',
    cost: { asset: 'operation', value: 35e2 },
    effect: [{ asset: 'wireQuantity', value: 1e3 }],
    available: true,
    quantity: 1,
  },
  wireBuyer: {
    category: 'wire',
    cost: { asset: 'operation', value: 7e3 },
    effect: { type: 'AUTO_BUY_WIRE' },
    available: true,
    quantity: 1,
  },
  microlatticeShapecasting: {
    category: 'wire',
    cost: { asset: 'operation', value: 75e2 },
    effect: [{ asset: 'wireQuantity', value: 1e4 }],
    available: true,
    quantity: 1,
  },
  spectralFrothAnnealment: {
    category: 'wire',
    cost: { asset: 'operation', value: 12e3 },
    effect: [{ asset: 'wireQuantity', value: 1e5 }],
    available: true,
    quantity: 1,
  },
  quantumFoamAnnealment: {
    category: 'wire',
    cost: { asset: 'operation', value: 15e3 },
    effect: [{ asset: 'wireQuantity', value: 1e6 }],
    available: true,
    quantity: 1,
  },
  wireDroneProcess: {
    category: 'drones',
    cost: { asset: 'operation', value: 25e3 },
    effect: ['wireDrone', 'clipFactory'],
    available: true,
    quantity: 1,
    // requirement: 'releaseHypnoDrone]
  },
};
