import type { ProductState } from '@/src/domains/factory/domain/product.type.ts';

export const PRODUCT_STATE: ProductState = {
  revTracker: {
    category: 'mechanic',
    cost: [{ asset: 'operation', value: 5e2 }],
    effects: ['fundsPerSecond'],
    available: true,
    quantity: 1,
  },
  anotherChance: {
    category: 'mechanic',
    cost: [{ asset: 'creativity', value: 7e4 }],
    effects: { type: 'ALLOCATE_TRUST' },
    available: false,
    quantity: 10,
    requirements: [{ asset: 'creativity', value: 7e4 }],
  },
  algorithmic: {
    category: 'investing',
    cost: [{ asset: 'operation', value: 1e4 }],
    effects: ['investments'],
    available: false,
    quantity: 0,
    requirements: [{ asset: 'trust', value: 8 }],
  },
  catchyJingle: {
    category: 'marketing',
    cost: [
      { asset: 'operation', value: 75e2 },
      { asset: 'creativity', value: 45 },
    ],
    effects: ['hypnoHarmonics'],
    available: false,
    quantity: 1,
    // requirements: ['combinatoryHarmonics'],
  },
  fullMonopoly: {
    category: 'marketing',
    cost: [
      { asset: 'funds', value: 1e7 },
      { asset: 'yomi', value: 3e3 },
    ],
    effects: [
      { asset: 'marketingBonus', value: 1e2 },
      { asset: 'trust', value: 1 },
    ],
    available: false,
    quantity: 1,
    requirements: [{ asset: 'funds', value: 1e7 }],
  },
  harvesterDroneProcess: {
    category: 'drones',
    cost: [{ asset: 'operation', value: 25e3 }],
    effects: ['harvesterDrone'],
    available: false,
    quantity: 1,
    // requirements: ['releaseHypnoDrone'],
  },
  hostileTakeover: {
    category: 'marketing',
    cost: [{ asset: 'funds', value: 1e6 }],
    effects: [
      { asset: 'marketingBonus', value: 10 },
      { asset: 'trust', value: 1 },
    ],
    available: false,
    quantity: 1,
    requirements: [{ asset: 'funds', value: 1e7 }],
  },
  hypnoHarmonics: {
    category: 'marketing',
    cost: [
      { asset: 'operation', value: 75e2 },
      { asset: 'trust', value: 1 },
    ],
    effects: ['hypnoDrone'],
    available: false,
    quantity: 1,
    // requirements: ['catchyJingle'],
  },
  hypnoDrone: {
    category: 'drones',
    cost: [{ asset: 'operation', value: 7e4 }],
    effects: ['releaseHypnoDrone'],
    available: false,
    quantity: 1,
    // requirements: ['hypnoHarmonics'],
  },
  improvedClipper: {
    category: 'production',
    cost: [{ asset: 'operation', value: 750 }],
    effects: [{ asset: 'clipperBonus', value: 2 }],
    available: false,
    quantity: 1,
    requirements: [{ asset: 'operation', value: 750 }],
  },
  evenBetterClipper: {
    category: 'production',
    cost: [{ asset: 'operation', value: 25e2 }],
    effects: [{ asset: 'clipperBonus', value: 10 }],
    available: false,
    quantity: 1,
    // requirements: ['improvedClipper'],
  },
  optimizedClipper: {
    category: 'production',
    cost: [{ asset: 'operation', value: 5e3 }],
    effects: [{ asset: 'clipperBonus', value: 100 }],
    available: false,
    quantity: 1,
    // requirements: ['evenBetterClipper'],
  },
  hadwigerClipDiagram: {
    category: 'production',
    cost: [{ asset: 'operation', value: 6e3 }],
    effects: [{ asset: 'clipperBonus', value: 500 }],
    available: false,
    quantity: 1,
    // requirements: ['hadwigerProblem'],
  },
  improvedMegaClipper: {
    category: 'production',
    cost: [{ asset: 'operation', value: 14e3 }],
    effects: [{ asset: 'megaClipperBonus', value: 2 }],
    available: false,
    quantity: 1,
    // requirements: ['megaClipper'],
  },
  evenBetterMegaClipper: {
    category: 'production',
    cost: [{ asset: 'operation', value: 17e3 }],
    effects: [{ asset: 'megaClipperBonus', value: 10 }],
    available: false,
    quantity: 1,
    // requirements: ['improvedMegaClipper'],
  },
  optimizedMegaClippers: {
    category: 'production',
    cost: [{ asset: 'operation', value: 195e2 }],
    effects: [{ asset: 'megaClipperBonus', value: 100 }],
    available: false,
    quantity: 1,
    // requirements: ['evenBetterMegaClipper'],
  },
  newSlogan: {
    category: 'marketing',
    cost: [
      { asset: 'operation', value: 25e2 },
      { asset: 'creativity', value: 25 },
    ],
    effects: [{ asset: 'marketingBonus', value: 2 }],
    available: false,
    quantity: 1,
  },
  releaseHypnoDrone: {
    category: 'drones',
    cost: [{ asset: 'trust', value: 1e2 }],
    effects: ['harvesterDroneProcess', 'wireDroneProcess'],
    available: false,
    quantity: 1,
  },
  begForMoreWire: {
    category: 'wire',
    cost: [{ asset: 'trust', value: 1 }],
    effects: [{ asset: 'funds', value: 100 }],
    available: false,
    quantity: 5,
  },
  improvedWireExtrusion: {
    category: 'wire',
    cost: [{ asset: 'operation', value: 1750 }],
    effects: [{ asset: 'wireQuantity', value: 5e2 }],
    available: false,
    quantity: 1,
  },
  optimizedWireExtrusion: {
    category: 'wire',
    cost: [{ asset: 'operation', value: 35e2 }],
    effects: [{ asset: 'wireQuantity', value: 1e3 }],
    available: false,
    quantity: 1,
  },
  wireBuyer: {
    category: 'wire',
    cost: [{ asset: 'operation', value: 7e3 }],
    // effects: { type: 'BUY_WIRE_AUTOMATICALLY' }, // @TODO
    effects: [],
    available: false,
    quantity: 1,
  },
  microlatticeShapecasting: {
    category: 'wire',
    cost: [{ asset: 'operation', value: 75e2 }],
    effects: [{ asset: 'wireQuantity', value: 1e4 }],
    available: false,
    quantity: 1,
  },
  spectralFrothAnnealment: {
    category: 'wire',
    cost: [{ asset: 'operation', value: 12e3 }],
    effects: [{ asset: 'wireQuantity', value: 1e5 }],
    available: false,
    quantity: 1,
  },
  quantumFoamAnnealment: {
    category: 'wire',
    cost: [{ asset: 'operation', value: 15e3 }],
    effects: [{ asset: 'wireQuantity', value: 1e6 }],
    available: false,
    quantity: 1,
  },
  wireDroneProcess: {
    category: 'drones',
    cost: [{ asset: 'operation', value: 25e3 }],
    effects: ['wireDrone', 'clipFactory'],
    available: false,
    quantity: 1,
    // requirements: ['releaseHypnoDrone']
  },
};
