import type { Merchandise } from '@/src/domains/merchandise/domain/merch.type.ts';

export const MERCHANDISE_STATE: Merchandise = {
  revTracker: {
    // @TODO
    category: 'mechanic',
    // cost: { asset: 'operation', value: 5e2 },
    cost: { asset: 'funds', value: 1 },
    effect: ['fundsPerSecond'],
    unlocked: true,
    purchased: false,
    quantity: 1,
  },
  offerAnotherChance: {
    // @TODO
    category: 'mechanic',
    cost: { asset: 'creativity', value: 7e4 },
    effect: { type: 'ALLOCATE_TRUST' },
    unlocked: true,
    purchased: true,
    // quantity: 10,
    quantity: 0,
    // requirement: { asset: 'creativity', value: 7e4 },
  },
  begForMoreWire: {
    category: 'wire',
    cost: { asset: 'trust', value: 1 },
    effect: [{ asset: 'funds', value: 100 }],
    unlocked: true,
    purchased: false,
    quantity: 5,
  },
  improvedWireExtrusion: {
    category: 'wire',
    cost: { asset: 'operation', value: 1750 },
    effect: [{ asset: 'wireQuantity', value: 5e2 }],
    unlocked: true,
    purchased: false,
    quantity: 1,
  },
  algorithmicTrading: {
    category: 'investing',
    cost: { asset: 'operation', value: 1e4 },
    effect: ['investments'],
    unlocked: true,
    purchased: false,
    quantity: 0,
    requirement: { asset: 'trust', value: 8 },
  },
  improvedClipper: {
    category: 'production',
    cost: { asset: 'operation', value: 750 },
    effect: [{ asset: 'clipperBonus', value: 2 }],
    unlocked: true,
    purchased: false,
    quantity: 1,
    requirement: { asset: 'operation', value: 750 },
  },
  evenBetterClipper: {
    category: 'production',
    cost: { asset: 'operation', value: 25e2 },
    effect: [{ asset: 'clipperBonus', value: 10 }],
    unlocked: true,
    purchased: false,
    quantity: 1,
    // requirement: 'improvedClipper',
  },
  optimizedClipper: {
    category: 'production',
    cost: { asset: 'operation', value: 5e3 },
    effect: [{ asset: 'clipperBonus', value: 100 }],
    unlocked: true,
    purchased: false,
    quantity: 1,
    // requirement: 'evenBetterClipper',
  },
  hadwigerClipDiagram: {
    category: 'production',
    cost: { asset: 'operation', value: 6e3 },
    effect: [{ asset: 'clipperBonus', value: 500 }],
    unlocked: true,
    purchased: false,
    quantity: 1,
    // requirement: 'hadwigerProblem',
  },
  improvedMegaClipper: {
    category: 'production',
    cost: { asset: 'operation', value: 14e3 },
    effect: [{ asset: 'megaClipperBonus', value: 2 }],
    unlocked: true,
    purchased: false,
    quantity: 1,
    // requirement: 'megaClipper',
  },
  evenBetterMegaClipper: {
    category: 'production',
    cost: { asset: 'operation', value: 17e3 },
    effect: [{ asset: 'megaClipperBonus', value: 10 }],
    unlocked: true,
    purchased: false,
    quantity: 1,
    // requirement: 'improvedMegaClipper',
  },
  optimizedMegaClipper: {
    category: 'production',
    cost: { asset: 'operation', value: 195e2 },
    effect: [{ asset: 'megaClipperBonus', value: 100 }],
    unlocked: true,
    purchased: false,
    quantity: 1,
    // requirement: 'evenBetterMegaClipper',
  },
  // @TODO: clipperMegaDiagrams
  newSlogan: {
    category: 'marketing',
    cost: { asset: 'operation', value: 25e2 },
    effect: [{ asset: 'marketingBonus', value: 2 }],
    unlocked: true,
    purchased: false,
    quantity: 1,
  },
  catchyJingle: {
    category: 'marketing',
    cost: { asset: 'operation', value: 75e2 },
    effect: ['hypnoHarmonic'],
    unlocked: true,
    purchased: false,
    quantity: 1,
    // requirement: 'combinatorHarmonic',
  },
  hypnoHarmonic: {
    category: 'marketing',
    cost: { asset: 'operation', value: 75e2 },
    effect: ['hypnoDrone'],
    unlocked: true,
    purchased: false,
    quantity: 1,
    // requirement: 'catchyJingle',
  },
  hostileTakeover: {
    category: 'marketing',
    cost: { asset: 'funds', value: 1e6 },
    effect: [
      { asset: 'marketingBonus', value: 10 },
      { asset: 'trust', value: 1 },
    ],
    unlocked: true,
    purchased: false,
    quantity: 1,
    requirement: { asset: 'funds', value: 1e7 },
  },
  fullMonopoly: {
    category: 'marketing',
    cost: { asset: 'funds', value: 1e7 },
    effect: [
      { asset: 'marketingBonus', value: 1e2 },
      { asset: 'trust', value: 1 },
    ],
    unlocked: true,
    purchased: false,
    quantity: 1,
    requirement: { asset: 'funds', value: 1e7 },
  },
  // @TODO: countyLimerick
  // @TODO: lexicalProcessing
  // @TODO: combinatorHarmonic
  hypnoDrone: {
    category: 'drones',
    cost: { asset: 'operation', value: 7e4 },
    effect: ['releaseHypnoDrone'],
    unlocked: true,
    purchased: false,
    quantity: 1,
    // requirement: 'hypnoHarmonic',
  },
  releaseHypnoDrone: {
    category: 'drones',
    cost: { asset: 'trust', value: 1e2 },
    effect: ['harvesterDroneProcess', 'wireDroneProcess'],
    unlocked: true,
    purchased: false,
    quantity: 1,
  },
  harvesterDroneProcess: {
    category: 'drones',
    cost: { asset: 'operation', value: 25e3 },
    effect: ['harvesterDrone'],
    unlocked: true,
    purchased: false,
    quantity: 1,
    // requirement: 'releaseHypnoDrone',
  },
  wireDroneProcess: {
    category: 'drones',
    cost: { asset: 'operation', value: 25e3 },
    effect: ['wireDrone', 'clipFactory'],
    unlocked: true,
    purchased: false,
    quantity: 1,
    // requirement: 'releaseHypnoDrone]
  },
  optimizedWireExtrusion: {
    category: 'wire',
    cost: { asset: 'operation', value: 35e2 },
    effect: [{ asset: 'wireQuantity', value: 1e3 }],
    unlocked: true,
    purchased: false,
    quantity: 1,
  },
  wireBuyer: {
    category: 'wire',
    cost: { asset: 'operation', value: 7e3 },
    effect: { type: 'AUTO_WIRE' },
    unlocked: true,
    purchased: false,
    quantity: 1,
  },
  microlatticeShapecasting: {
    category: 'wire',
    cost: { asset: 'operation', value: 75e2 },
    effect: [{ asset: 'wireQuantity', value: 1e4 }],
    unlocked: true,
    purchased: false,
    quantity: 1,
  },
  spectralFrothAnnealment: {
    category: 'wire',
    cost: { asset: 'operation', value: 12e3 },
    effect: [{ asset: 'wireQuantity', value: 1e5 }],
    unlocked: true,
    purchased: false,
    quantity: 1,
  },
  quantumFoamAnnealment: {
    category: 'wire',
    cost: { asset: 'operation', value: 15e3 },
    effect: [{ asset: 'wireQuantity', value: 1e6 }],
    unlocked: true,
    purchased: false,
    quantity: 1,
  },
};
